### ISSUE TITLE
How to use it with ng serve

### ISSUE THREAD

**Issue by mferlay** [rfreedman/angular-configuration-service#2]
Hi rfreedman and thanks for this explaination. I have reuse your concept in my project to externalize the environment url as properties set by spring and it works really well.

I have just a little question. As part of my dev is in Angular, I use a ng server to not rebuild all my project when I modify only this part. But with your way, I don't manage to run it in correctly now.

My backend run on localhost:8080 but my ng serve understand only localhost:4200.  before I used the environment.ts to replace the url and call the right api url. 

Could you tell how do you manage to do the same with your technic? Maybe I need to implement also the proxy part?

best regards

**Comment by rfreedman** [comment]
Yes, in that situation, I use the proxy to get the API calls to the spring
back-end.

**Comment by mferlay** [comment]
thanks
